registry:
  restart: always
  image: registry
  ports:
    - 443:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
    REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
    # REGISTRY_HTTP_ADDR: :5000
    # REGISTRY_AUTH: htpasswd
    # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - ./registry/data:/var/lib/registry
    - ./registry/certs:/certs
    - ./registry/auth:/auth
  labels:
    io.rancher.scheduler.affinity:host_label: registry.enabled=true