registry:
  restart: always
  image: registry
  ports:
    - 5000:5000
  environment:
    # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
    # REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
    REGISTRY_HTTP_ADDR: :5000
    # REGISTRY_AUTH: htpasswd
    # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /docker/registry/data:/var/lib/registry
    - /docker/registry/certs:/certs
    - /docker/registry/auth:/auth
  labels:
    io.rancher.scheduler.affinity:host_label: registry.enabled=true

nginx:
  image: "nginx"
  ports:
    - 443:443
  links:
    - registry
  volumes:
    - /docker/registry/config/nginx:/etc/nginx/conf.d
  labels:
    io.rancher.scheduler.affinity:host_label: registry.enabled=true
# ssl:
#   image: containersol/docker-registry-proxy
#   ports:
#     - 443:443
#   links:
#     - registry
#   environment:
#     REGISTRY_HOST: "registry"
#     REGISTRY_PORT: "5000"
#     SERVER_NAME: "docker-cn.tutormeet.plus"
#   volumes:
#     - /docker/registry/auth/htpasswd:/etc/nginx/.htpasswd:ro
#     - /docker/registry/certs/fullchain.pem:/etc/nginx/ssl/docker-registry.crt:ro
#     - /docker/registry/certs/privkey.pem:/etc/nginx/ssl/docker-registry.key:ro
#   labels:
#     io.rancher.scheduler.affinity:host_label: registry.enabled=true
# docker run -p 443:443 \
#     -e REGISTRY_HOST="docker-registry" \
#     -e REGISTRY_PORT="5000" \
#     -e SERVER_NAME="localhost" \
#     --link docker-registry:docker-registry \
#     -v $(pwd)/.htpasswd:/etc/nginx/.htpasswd:ro \
#     -v $(pwd)/certs:/etc/nginx/ssl:ro \
#     containersol/docker-registry-proxy
# docker run --entrypoint htpasswd registry:2 -Bbn tutor tutor > /docker/registry/auth/htpasswd